---
- name: Manage Docker users
  hosts: docker_server
  become: yes # Run tasks with elevated privileges (sudo)

  tasks:
  # Ensure that the 'docker' group exists on the server
  - name: Ensure docker group exists
    group:
      name: docker
      state: present

  # Add the 'ubuntu' user to the 'docker' group
  # Using append: yes ensures existing group memberships are preserved
  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  # Inform the user that group membership changes require a new session
  - name: Reminder for group membership refresh
    debug:
      msg: "Ubuntu user has been added to the docker group. Please log out and log back in (or restart SSH session) for this to take effect."
