---
- name: Docker Login
  hosts: docker_server
  become: yes

  vars_files:
  - vault.yml # Store username & password securely with Ansible Vault

  tasks:
  - name: Log in to Docker Hub
    community.docker.docker_login:
      username: "{{ docker_username }}"
      password: "{{ docker_password }}"
